config/routes.rb
Clasesde::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :grades
  resources :messages
  resources :users do
    collection do
      get :account
    end
  end

  root 'grades#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages, as: :from

  def name
    email
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :category
  has_many :grade_users
  has_many :lessons
  has_many :users, :through => :grade_users
end

app/models/grade_user.rb
class GradeUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :grade

  validates_uniqueness_of :grade_id, :scope => :user_id
  # before_save :check_exists
  #
  # def check_exists
  #   not GradeUser.where(user: self.user, grade: self.grade).any?
  # end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :grade
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :from, polymorphic: true
  belongs_to :to, polymorphic: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :grade_users
  has_many :grades, :through => :grade_users
  has_many :messages, as: :from
  has_many :admin_messages, as: :to, class_name: "Message"

  has_many :user_messages,   as: :from, class_name: "Message"
  # has_many :admin_messages, class_name: "Message", conditions: {"messages.to_id" => "users.id", "messages.to_type" => "User"}
  # has_many :admin_messages, :through => :messages_, source: :to, source_type: "User"


  accepts_nested_attributes_for :grades, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :grade_users, :reject_if => :all_blank, :allow_destroy => true

  def name
    "#{first_name} #{last_name}" || email
  end

  def messages_
    (user_messages + admin_messages).sort_by{|e| e.created_at}.reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :authenticate_user!

  def index
    @grades = current_user.grade_users
  end

  def show
    @grade = current_user.grades.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def create
    @message = current_user.messages.new message_params

    respond_to do |format|
      if @message.save
        AppMail.send_message(@message, current_user, "contacto@clasesde.cl").deliver
        format.html { redirect_to  messages_path}
      else
        format.html { render :index}
      end
    end
  end

  def message_params
    params.require(:message).permit(:message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def account
  end

  def update
    respond_to do |format|
      if current_user.update_attributes(user_params)
        format.html {redirect_to account_users_path}
      else
        format.html {render :account}
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :age, :password, :password_confirm)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/app_mail/send_message.html.haml
Mensaje de

app/views/grades/index.html.haml
- if @grades.any?
  %ul.small-block-grid-1.large-block-grid-2.grades
    - @grades.each do |g|
      - if g.grade.present?
        %li
          %h2= g.grade.name
          .info
            .row
              .large-12.columns
                = truncate(g.grade.description, length: 100)
            .row
              .large-12.columns
                = link_to "ver clase", grade_path(g.grade), class: "button button-black"
- else
  .alert-box.warning{"data-alert" => ""}
    No tienes clases asignadas

app/views/grades/show.html.haml
%ul.breadcrumbs
  %li
    %a{href: grades_path} Home
  %li
    %a{href: grade_path(@grade)}
      = @grade.name

%h2= @grade.name
.description
  = raw @grade.description

%hr
- @grade.lessons.each do |l|
  .lesson
    %h3= l.title
    .content
      = raw l.content
    %hr

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Clasesde
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic", rel: "stylesheet", type: "text/css"
    = csrf_meta_tags
  %body
    .large-12.columns.large-centered.text-center.header
      .row
        = image_tag "http://www.clasesde.cl/wp-content/themes/clasesde/images/logo.png", class: 'text-center'
      .row
        %nav.top-bar{"data-topbar" => ""}
          %ul.title-area
            %li.name
              %h1
                %a{:href => "#"}
            / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
            %li.toggle-topbar.menu-icon
              %a{:href => "#"}
                %span
          %section.top-bar-section
            / Right Nav Section
            %ul.right
              %li
                %a{:href => "/"}
                  %i.fa.fa-home
                  Inicio

              - if user_signed_in?
                %li
                  = link_to account_users_path do
                    %i.fa.fa-cog
                    Cuenta personal
                %li
                  = link_to messages_path do
                    %i.fa.fa-envelope
                    Mensaje
                %li
                  = link_to destroy_user_session_path, :method => 'delete' do
                    %i.fa.fa-power-off
                    Salir

    .row.content
      .large-12.columns
        = yield

    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/layouts/awesome.html.haml
!!!
%html{lang: "es"}
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %meta{"http-equiv" => "Content-Type", content: "text/html; charset=UTF-8"}

  %body{:bgcolor => "#b03e3e", :leftmargin => "0", :marginheight => "0", :marginwidth => "0", :style => "margin: 0px; background-color: #f7f2e4;", :topmargin => "0"}
    / 100% body table
    %table{:bgcolor => "#b03e3e", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
      %tr
        %td
          / header
          %table{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :style => "background:url(images/header-bg.jpg); background-repeat: no-repeat; background-position: center; background-color: #fffdf9;", :width => "684"}
            %tr
              %td
                %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                  %tr
                    %td{:valign => "middle", :width => "100%"}
                      %table{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                        %tr
                          %td{:height => "60"}
                        %tr
                          %td
                            %h1{:style => "color: #333; margin-top: 0px; margin-bottom: 0px;text-align: center; font-weight: normal; font-size: 48px; font-family: Georgia, 'Times New Roman', Times, serif"}
                              Clasesde.cl
          / /header
          / email container
          %table{:align => "center", :bgcolor => "#fffdf9", :border => "0", :cellpadding => "30", :cellspacing => "0", :width => "684"}
            %tr
              %td
                / email content
                %table#email-content{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "624"}
                  %tr
                    %td
                      / section 1
                      %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                        %tr
                          %td{:align => "left", :valign => "top"}

                            / /line break
                            %h1{:style => "font-size: 36px; font-weight: normal; color: #333333; font-family: Georgia, 'Times New Roman', Times, serif; margin-top: 0px; margin-bottom: 20px;"}
                              Nuevo mensaje
                            %p{:style => "font-size: 16px; line-height: 22px; font-family: Georgia, 'Times New Roman', Times, serif; color: #333; margin: 0px;"}
                              Tienes un nuevo mensaje de #{@user.name}(#{@user.email})
                            %p{:style => "font-size: 16px; line-height: 22px; font-family: Georgia, 'Times New Roman', Times, serif; color: #333; margin: 0px;"}
                              Mensaje: #{@message.message}
                            %p
                              Puedes responder este mensaje ingresando
                              - if @user.class.name.underscore == "user"
                                = link_to "aquí", "http://app.clasesde.cl/admin/login", target: "_blank"
                              - else
                                = link_to "aquí", "http://app.clasesde.cl", target: "_blank"


                / /email content
          / /email container
          / footer
          %table{:align => "center", :border => "0", :cellpadding => "30", :cellspacing => "0", :width => "680"}
            %tr
              %td{:valign => "top"}
                %p{:style => "font-size: 14px; line-height: 24px; font-family: Georgia, 'Times New Roman', Times, serif; color: #b0a08b; margin: 0px;"}
                  clasesde.cl
            %tr
              %td{:height => "30"}
              %td{:height => "30"}
          / /footer
    / /100% body table

app/views/messages/index.html.haml
%ul.breadcrumbs
  %li
    %a{href: grades_path} Home
  %li
    %a{href: "javascript:;"}
      Mensajes

%h2 Mensajes

= simple_form_for Message.new do |f|
  = f.input :message, as: :text
  = f.submit "enviar mensaje", class: 'button'


.messages
  - current_user.messages_.each do |m|
    .row
      .message-box.large-8.columns.nopadding{class: m.from.class.name.underscore}
        .header
          %h3
            Mensaje de #{m.from.name || "dda"}
        .message
          = m.message

app/views/users/account.html.haml
%ul.breadcrumbs
  %li
    %a{href: grades_path} Home
  %li
    %a{href: "#"}
      Tu cuenta

%h2 Cuenta personal

= simple_form_for current_user do |f|
  .row
    .large-8.columns
      .row
        .large-12.columns
          = f.label "email"
          = f.text_field :email
          = f.error :email
      .row
        .large-12.columns
          = f.label "nombre"
          = f.text_field :first_name
      .row
        .large-12.columns
          = f.label "apellido"
          = f.text_field :last_name
      .row
        .large-12.columns
          = f.label "edad"
          = f.text_field :age

      = f.submit "modificar", class: 'button button-black'

%hr
%h2 Modificar contraseña
= simple_form_for current_user do |f|
  .row
    .large-8.columns
      .row
        .large-12.columns
          = f.label "contraseña"
          = f.password_field :password
          = f.error :password
      .row
        .large-12.columns
          = f.label "confirmar contraseña"
          = f.password_field :password_confirmation
          = f.error :password_confirmation

      = f.submit "modificar contraseña", class: 'button button-black'